const skills = {
  'C': 'c.png',
  'C++': 'cpp.png',
  'C#': 'cs.png',
  'Java': 'java.png',
  'Javascript': 'js.png',
  'Python': 'python.png',
  'React': 'react.png',
  'IOS': 'ios.png',
  'Android': 'android.png',
  'Flutter': 'flutter.png',
  'NodeJS': 'nodejs.png',
  'PHP': 'php.png',
  'Dart': 'dart.png',
  'AWS': 'aws.png',
  'MySQL': 'mysql.png',
  'CI/CD': 'cicd.png',
  'Go': 'go.png',
  'Kotlin': 'kotlin.png',
};
